### PR TITLE
Switch to TypeScript, fix #16

### LINKED ISSUE #16: Use user display name instead of their unique name
e.g LandarVargan instead of landarvargan 
image

### PR DESCRIPTION
**Pull request by AFCMS**
- [x] Switch to TypeScript
- [x] Fix https://github.com/MT-CTF/ctf-discord-bot/issues/16 ~~(waiting for Discord.js release, code prepared for it)~~
~~- [ ] Implement some more features like #1 ?~~

@LoneWolfHT

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
#1 can be ignored for now

**Comment by AFCMS** [comment]
I will perhaps do more refactoring to prepare codebase to #16 and #18

**Comment by AFCMS** [comment]
Discord.js update juste landed

I will try to finish thé PR in the next few days

**Comment by AFCMS** [comment]
I looked into the possibility of using the global name or the server nickname instead of the username for the /x staff command. IDK what characters Minetest support compared to what is allowed in Discord, so I didn't implement this feature.

Anyway I consider this PR as ready for review @LoneWolfHT

**Comment by LoneWolfHT** [comment]
> I looked into the possibility of using the global name or the server nickname instead of the username for the /x staff command. IDK what characters Minetest support compared to what is allowed in Discord, so I didn't implement this feature.

If you can strip out everything but `a-zA-Z0-9_-` from the names I think that'll be enough.

> Anyway I consider this PR as ready for review @LoneWolfHT

It'll be a few more days before I can test. Thanks

**Comment by AFCMS** [comment]
Fixed a problem with the http server and used the nickname/globalname instead of the username when possible.

**Pull request merged**
